import mongoose from 'mongoose';
import Car from './models/Car.js';
import User from './models/User.js';
import dotenv from 'dotenv';

dotenv.config();

async function seedCars() {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI || process.env.MONGO_URI);
    console.log('Connected to MongoDB');

    // Find admin user
    const admin = await User.findOne({ role: 'admin' });
    if (!admin) {
      console.error('Admin user not found');
      process.exit(1);
    }

    console.log(`Using admin user: ${admin._id}`);

    // Sample cars data with real car images
    const carsData = [
      {
        name: 'Honda City',
        brand: 'Honda',
        model: 'City',
        year: 2023,
        type: 'Sedan',
        category: 'Indian',
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Manual',
        pricePerDay: 3000,
        location: 'Mumbai',
        description: 'Reliable and fuel-efficient sedan perfect for city driving.',
        features: ['ABS', 'Power Steering', 'Air Conditioning', 'Radio/CD Player'],
        images: [{ url: 'https://images.unsplash.com/photo-1552519507-da3effca6e5a?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 4.5,
        numReviews: 12,
      },
      {
        name: 'Toyota Fortuner',
        brand: 'Toyota',
        model: 'Fortuner',
        year: 2022,
        type: 'SUV',
        category: 'Premium',
        seats: 7,
        fuelType: 'Diesel',
        transmission: 'Automatic',
        pricePerDay: 5500,
        location: 'Delhi',
        description: 'Spacious SUV with powerful engine and luxurious interiors.',
        features: ['4WD', 'Leather Seats', 'Sunroof', 'Navigation System'],
        images: [{ url: 'https://images.unsplash.com/photo-1606611013016-969c19d14311?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 4.8,
        numReviews: 25,
      },
      {
        name: 'Maruti Swift',
        brand: 'Maruti',
        model: 'Swift',
        year: 2023,
        type: 'Hatchback',
        category: 'Economy',
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Manual',
        pricePerDay: 2000,
        location: 'Bangalore',
        description: 'Compact and economical hatchback ideal for budget travelers.',
        features: ['Power Windows', 'Central Locking', 'Air Conditioning'],
        images: [{ url: 'https://images.unsplash.com/photo-1507950547674-bcb2b5d41237?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 4.3,
        numReviews: 18,
      },
      {
        name: 'BMW 7 Series',
        brand: 'BMW',
        model: '7 Series',
        year: 2023,
        type: 'Sedan',
        category: 'Luxury',
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        pricePerDay: 15000,
        location: 'Mumbai',
        description: 'Ultimate luxury sedan with advanced technology and comfort.',
        features: ['Leather Interior', 'Panoramic Sunroof', 'Adaptive Cruise Control', 'Premium Sound System'],
        images: [{ url: 'https://images.unsplash.com/photo-1567818735868-e71b99932e29?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 5,
        numReviews: 8,
      },
      {
        name: 'Mercedes-Benz C-Class',
        brand: 'Mercedes-Benz',
        model: 'C-Class',
        year: 2022,
        type: 'Sedan',
        category: 'Luxury',
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        pricePerDay: 12000,
        location: 'Hyderabad',
        description: 'Elegant luxury sedan with superior driving experience.',
        features: ['AMG Exterior', 'Leather Seats', 'Dual Climate Control'],
        images: [{ url: 'https://images.unsplash.com/photo-1535732066927-ab7c9ab60908?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 4.9,
        numReviews: 15,
      },
      {
        name: 'Hyundai Creta',
        brand: 'Hyundai',
        model: 'Creta',
        year: 2023,
        type: 'SUV',
        category: 'Premium',
        seats: 5,
        fuelType: 'Diesel',
        transmission: 'Automatic',
        pricePerDay: 4500,
        location: 'Chennai',
        description: 'Stylish compact SUV with excellent fuel efficiency.',
        features: ['Touchscreen', 'Rear Parking Camera', 'Cruise Control'],
        images: [{ url: 'https://images.unsplash.com/photo-1609506026858-e51b4e9f17d9?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 4.6,
        numReviews: 22,
      },
      {
        name: 'Tata Safari',
        brand: 'Tata',
        model: 'Safari',
        year: 2022,
        type: 'SUV',
        category: 'Premium',
        seats: 7,
        fuelType: 'Diesel',
        transmission: 'Automatic',
        pricePerDay: 5000,
        location: 'Pune',
        description: '3-row SUV with comfortable seating and great performance.',
        features: ['Automatic Headlamps', 'Terrain Response', 'ISOFIX Mounts'],
        images: [{ url: 'https://images.unsplash.com/photo-1606611013016-969c19d14311?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 4.7,
        numReviews: 20,
      },
      {
        name: 'Mahindra XUV700',
        brand: 'Mahindra',
        model: 'XUV700',
        year: 2023,
        type: 'SUV',
        category: 'Premium',
        seats: 7,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        pricePerDay: 4800,
        location: 'Kolkata',
        description: 'Modern SUV with cutting-edge technology and spacious interior.',
        features: ['ADAS', 'Panoramic Sunroof', 'Connected Car Tech'],
        images: [{ url: 'https://images.unsplash.com/photo-1552519507-da3effca6e5a?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 4.8,
        numReviews: 19,
      },
      {
        name: 'Audi A6',
        brand: 'Audi',
        model: 'A6',
        year: 2023,
        type: 'Sedan',
        category: 'Luxury',
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        pricePerDay: 13000,
        location: 'Bangalore',
        description: 'Premium sedan with sportiness and advanced features.',
        features: ['Virtual Cockpit', 'Adaptive Air Suspension', 'Bang & Olufsen Sound'],
        images: [{ url: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 4.9,
        numReviews: 14,
      },
      {
        name: 'Skoda Superb',
        brand: 'Skoda',
        model: 'Superb',
        year: 2022,
        type: 'Sedan',
        category: 'Premium',
        seats: 5,
        fuelType: 'Diesel',
        transmission: 'Automatic',
        pricePerDay: 6000,
        location: 'Delhi',
        description: 'Spacious sedan with German engineering and comfort.',
        features: ['Digital Cockpit', 'Panoramic Sunroof', 'LED Headlights'],
        images: [{ url: 'https://images.unsplash.com/photo-1552519507-da3effca6e5a?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 4.7,
        numReviews: 17,
      },
      {
        name: 'Volkswagen Tiguan',
        brand: 'Volkswagen',
        model: 'Tiguan',
        year: 2023,
        type: 'SUV',
        category: 'Premium',
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        pricePerDay: 5200,
        location: 'Mumbai',
        description: 'Compact SUV with powerful engine and premium features.',
        features: ['4MOTION AWD', 'Panoramic Sunroof', 'Digital Cockpit'],
        images: [{ url: 'https://images.unsplash.com/photo-1609506026858-e51b4e9f17d9?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 4.8,
        numReviews: 21,
      },
      {
        name: 'Kia Seltos',
        brand: 'Kia',
        model: 'Seltos',
        year: 2023,
        type: 'SUV',
        category: 'Premium',
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Manual',
        pricePerDay: 3800,
        location: 'Hyderabad',
        description: 'Stylish compact SUV with modern tech and great value.',
        features: ['Touchscreen', 'Wireless Charging', 'Panoramic Sunroof'],
        images: [{ url: 'https://images.unsplash.com/photo-1606611013016-969c19d14311?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 4.6,
        numReviews: 16,
      },
      {
        name: 'Jaguar F-PACE',
        brand: 'Jaguar',
        model: 'F-PACE',
        year: 2022,
        type: 'SUV',
        category: 'Luxury',
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        pricePerDay: 14000,
        location: 'Chennai',
        description: 'Luxury sports SUV with dramatic design and performance.',
        features: ['Panoramic Sunroof', 'Adaptive Dynamics', 'Merridan Sound System'],
        images: [{ url: 'https://images.unsplash.com/photo-1606611013016-969c19d14311?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 4.9,
        numReviews: 11,
      },
      {
        name: 'Porsche 911',
        brand: 'Porsche',
        model: '911',
        year: 2023,
        type: 'Coupe',
        category: 'Luxury',
        seats: 4,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        pricePerDay: 20000,
        location: 'Mumbai',
        description: 'Iconic sports car with legendary performance and style.',
        features: ['Sport Chrono Package', 'Panoramic Sunroof', 'Premium Sound'],
        images: [{ url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 5,
        numReviews: 9,
      },
      {
        name: 'Lamborghini Huracán',
        brand: 'Lamborghini',
        model: 'Huracán',
        year: 2022,
        type: 'Coupe',
        category: 'Luxury',
        seats: 2,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        pricePerDay: 25000,
        location: 'Delhi',
        description: 'High-performance supercar with breathtaking acceleration.',
        features: ['Carbon Fiber Interior', 'Active Aerodynamics', 'Brembo Brakes'],
        images: [{ url: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 5,
        numReviews: 7,
      },
      {
        name: 'Ferrari F8 Tributo',
        brand: 'Ferrari',
        model: 'F8 Tributo',
        year: 2023,
        type: 'Coupe',
        category: 'Luxury',
        seats: 2,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        pricePerDay: 30000,
        location: 'Bangalore',
        description: 'Italian masterpiece combining power, elegance, and tradition.',
        features: ['Karbon Seats', 'Active Aerodynamics', 'Carbon Fiber Trim'],
        images: [{ url: 'https://images.unsplash.com/photo-1569480203946-2b2f4c2bc223?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 5,
        numReviews: 6,
      },
      {
        name: 'Rolls-Royce Phantom',
        brand: 'Rolls-Royce',
        model: 'Phantom',
        year: 2023,
        type: 'Sedan',
        category: 'Luxury',
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        pricePerDay: 35000,
        location: 'Mumbai',
        description: 'The ultimate expression of luxury and craftsmanship.',
        features: ['Starlight Headliner', 'Phantom Leather', 'Whisper Ride'],
        images: [{ url: 'https://images.unsplash.com/photo-1544331331-c66eb0ceafa0?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 5,
        numReviews: 5,
      },
      {
        name: 'Mahindra Thar',
        brand: 'Mahindra',
        model: 'Thar',
        year: 2023,
        type: 'SUV',
        category: 'Premium',
        seats: 4,
        fuelType: 'Diesel',
        transmission: 'Manual',
        pricePerDay: 4200,
        location: 'Pune',
        description: 'Legendary off-road SUV with rugged appeal and capability.',
        features: ['4WD', 'Roll Cage', 'All-Terrain Tires'],
        images: [{ url: 'https://images.unsplash.com/photo-1606611013016-969c19d14311?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 4.7,
        numReviews: 23,
      },
      {
        name: 'Force Gurkha',
        brand: 'Force',
        model: 'Gurkha',
        year: 2022,
        type: 'SUV',
        category: 'Premium',
        seats: 4,
        fuelType: 'Diesel',
        transmission: 'Manual',
        pricePerDay: 3600,
        location: 'Kolkata',
        description: 'True off-road vehicle with exceptional durability.',
        features: ['4WD', 'Ladder Frame', 'Solid Axles'],
        images: [{ url: 'https://images.unsplash.com/photo-1606611013016-969c19d14311?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 4.5,
        numReviews: 13,
      },
      {
        name: 'Maruti Brezza',
        brand: 'Maruti',
        model: 'Brezza',
        year: 2023,
        type: 'SUV',
        category: 'Economy',
        seats: 5,
        fuelType: 'Diesel',
        transmission: 'Manual',
        pricePerDay: 2800,
        location: 'Ahmedabad',
        description: 'Affordable compact SUV perfect for everyday commute.',
        features: ['Power Steering', 'Air Conditioning'],
        images: [{ url: 'https://images.unsplash.com/photo-1606611013016-969c19d14311?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 4.4,
        numReviews: 24,
      },
      {
        name: 'Tata Nexon',
        brand: 'Tata',
        model: 'Nexon',
        year: 2023,
        type: 'SUV',
        category: 'Economy',
        seats: 5,
        fuelType: 'Diesel',
        transmission: 'Automatic',
        pricePerDay: 3200,
        location: 'Surat',
        description: 'Compact SUV with bold design and practical features.',
        features: ['ABS', 'Touchscreen', 'Fog Lamps'],
        images: [{ url: 'https://images.unsplash.com/photo-1606611013016-969c19d14311?w=500&h=400&fit=crop' }],
        owner: admin._id,
        isApproved: true,
        isAvailable: true,
        rating: 4.5,
        numReviews: 20,
      },
    ];

    // Delete existing cars (optional)
    await Car.deleteMany({ owner: admin._id });
    console.log('Cleared existing cars');

    // Insert cars
    const insertedCars = await Car.insertMany(carsData);
    console.log(`✅ Successfully added ${insertedCars.length} cars to the database!`);

    // Show summary
    console.log('\nCars added:');
    insertedCars.forEach((car, idx) => {
      console.log(`${idx + 1}. ${car.name} - ₹${car.pricePerDay}/day`);
    });

    await mongoose.connection.close();
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding cars:', error.message);
    process.exit(1);
  }
}

seedCars();
